# ./.devcontainer/dockerfile

FROM golang:1.22

# Docker 클라이언트 설치
# RUN apt-get update && apt-get install -y \
#     apt-transport-https \
#     ca-certificates \
#     curl \
#     gnupg2 \
#     software-properties-common
    
# Git 브랜치 정보를 가져오는 함수와 프롬프트 설정 추가
RUN echo 'parse_git_branch() {' >> ~/.bashrc && \
    echo '  git branch 2>/dev/null | grep "* " | sed "s/* //"' >> ~/.bashrc && \
    echo '}' >> ~/.bashrc && \
    echo 'export PS1="\[\033[01;34m\]\u@\h \[\033[01;32m\]\w \[\033[01;33m\](\$(parse_git_branch))\[\033[00m\] $ "' >> ~/.bashrc

# Install gofumpt, golines, and golangci-lint
RUN go install mvdan.cc/gofumpt@latest \
    && go install github.com/segmentio/golines@latest \
    && go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    
# 작업 디렉토리 설정
WORKDIR /app

RUN go install github.com/swaggo/swag/cmd/swag@latest

CMD [ "sleep", "infinity" ]