# ./.devcontainer/docker-compose.yml
version: '3.8'

services:
  back:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ../:/app
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro

    command: sleep infinity
